apiVersion: v1
data:
  token: "YThkNGE0YmUtZjFjYS00MTY0LTljYzktNmViNzk2OWU4NzVk"
kind: Secret
metadata:
  annotations:
    description: Aqua Enforcer token secret
  creationTimestamp: null
  labels:
    deployedby: aqua-yaml
  name: enforcer-token
  namespace: aqua
type: Opaque
