apiVersion: v1
data:
  token: "YTBmMWIyMmItOWExOC00YzU3LWIxOTEtYWZiYzRkZTRjZWI0"
kind: Secret
metadata:
  annotations:
    description: Aqua Enforcer token secret
  creationTimestamp: null
  labels:
    deployedby: aqua-yaml
  name: enforcer-token
  namespace: aqua
type: Opaque
