#
---

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: aqua-scanner-pvc
#  namespace: aqua
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: aqua-scanner
  name: aqua-scanner
  namespace: aqua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-scanner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aqua-scanner
    spec:
      containers:
      - args:
        - -c
        - /opt/aquasec/scannercli daemon --host https://${AQUA_SERVER} --user ${AQUA_SCANNER_USERNAME}
          --password ${AQUA_SCANNER_PASSWORD}  --no-verify
        command:
        - /bin/sh
        env:
        - name: AQUA_SCANNER_LOGICAL_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: aqua-scanner
        image: registry.aquasec.com/scanner:6.2
        imagePullPolicy: IfNotPresent
        name: kube-scanner
        resources: {}
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs
          readOnly: true
      imagePullSecrets:
      - name: aqua-registry
      securityContext:
        fsGroup: 11433
        runAsGroup: 11433
        runAsUser: 11431
      serviceAccount: aqua-sa
      serviceAccountName: aqua-sa
      volumes:
      - name: ssl-certs
        secret:
          items:
          - key: aqua-web-root-cert
            path: aqua-ssl.crt
          secretName: aqua-scanner
status: {}
